server:
  port: 8848
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: shanyigou-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/llii-ii/shanyigou-config.git
          username: 583979704@qq.com
          password: l0852963...